### ISSUE TITLE
Update TeX-FPC and give credit to CTAN resp. Wolfgang Helbig

### ISSUE THREAD

**Issue by btreut** [Alexey-T/TeX-FPC#1]
Hi Alexey,

the version on CTAN has been updated since creation of your repository here, see [files on CTAN](https://www.ctan.org/ctan-ann/pkg/tex-fpc). So it would be nice, if you could update your repo to the current state. Already knowing about TeX-GPX and having had contact with Wolfgang Helbig some years ago, I checked CTAN after stumbling over your repo and having seen that the Readme.md was "signed" by Wolfgang Helbig  ...

regards,  Bernhard

**Comment by Alexey-T** [comment]
we have a problem to update it. I cannot download one file with all content (so I must download all small files 1 by 1).
from https://mirror.macomnet.net/pub/CTAN/systems/unix/tex-fpc/
give me the entire TeX-FPC in one file, pls?

**Comment by ascherer** [comment]
Head over to https://ctan.org/pkg/tex-fpc and click on "Herunterladen"/"Download".

**Comment by btreut** [comment]
> [...]  give me the entire TeX-FPC in one file, pls?

I append it here: 
[tex-fpc.zip](https://github.com/user-attachments/files/16439962/tex-fpc.zip)

**Comment by Alexey-T** [comment]
Updated. if ok, close the issue.
